# Generated by Django 3.0.4 on 2020-05-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boutique',
            index=models.Index(fields=['name'], name='shop_boutiq_name_bd9f9f_idx'),
        ),
    ]
