# POST https://us15.api.mailchimp.com/3.0/ecommerce/stores HTTP/1.1
# Content-Type: application/json
# Authorization: auth 03351c2235cfe08e38995805b658311c-us15

# {
#     "merge_fields": {}
# }

# POST https://us15.api.mailchimp.com/3.0/ecommerce/stores HTTP/1.1
# Content-Type: application/json
# Authorization: auth 03351c2235cfe08e38995805b658311c-us15

# {
#     "id": "3b0c488c2c05b569914e",
#     "list_id": "3335ddb952",
#     "name": "Nawoka",
#     "domain": "https://nawoka.fr",
#     "currency_code": "EUR",
#     "email": "contact.nawoka@gmail.com",
#     "merge_fields": {},
#     "money_format": "€",
#     "primary_locale": "fr",
#     "phone": "0668552975", 
#     "address": { "city": "Lille", "country": "France" }
# }

POST https://us15.api.mailchimp.com/3.0/ecommerce/stores/3b0c488c2c05b569914e/customers HTTP/1.1
Content-Type: application/json
Authorization: auth 03351c2235cfe08e38995805b658311c-us15

{
    "id": "zezofizoeifnze",
    "merge_fields": {
        
    },
    "customer": {
        "id": "64e8396cda3a9b5e50fd",   
    },
    "currency_code": "EUR",
    "orders_count": 175,
    "discount_total": 0,
    "shipping_total": 175,
    "processed_at_foreign": "01-01-2019",
    "shipping_address": {
        "name": "",
        "address1": "",
        "address2": "",
        "city": "",
        "postal_code": "",
        "country": "",
        "country_code": ""
    },
    "financial_status": "pending",
    "lines": [
        {
            "id": "zenfzoifenzo",
            "product_id": "iznoeinzoenf",
            "quantity": 1,
            "price": 12.745,
            "discount": 0
        }
    ]
}