version: '3'

services:
  db:
    build: ./database
    # image: postgres:latest
    # restart: always
    # environment:
    #   - POSTGRES_USER='john'
    #   - POSTGRES_PASSWORD='Constance97170'
    #   - POSTGRES_DB='lang1'
    #   - POSTGRES_USER=$POSTGRES_USER
    #   - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    #   - POSTGRES_DB=$POSTGRES_DB
    # volumes:
    #   - ./init:/docker-entrypoint-initdb.d/

  # guni:
  #   build: ./gunicorn
    # command: python3 --bind 0.0.0.0:8000 0.0.0.0:8000.sock
      
  mysite:
    # container_name: language-startup
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    volumes:
      - .:/code
      # - ./logs:/var/log
      # - ./config:/etc/appconfig
    ports:
      - "8000:8000"
    depends_on:
      - db

  mynginx:
    build: ./nginx/
    # command: service nginx configtest
    restart: always
    ports:
      - "8080:80"
    # volumes:
    #  - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - mysite:mysite
