# Generated by Django 2.0.4 on 2018-05-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('candidat', models.BooleanField(default=False)),
                ('entreprise', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.IntegerField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('contrat_recherche', models.CharField(blank=True, max_length=100, null=True)),
                ('secteur_recherche', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_une', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_deux', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_trois', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_quatre', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_cinq', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_une', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_une_description', models.TextField(blank=True, null=True)),
                ('experience_deux', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_deux_description', models.TextField(blank=True, null=True)),
                ('experience_trois', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_trois_description', models.TextField(blank=True, null=True)),
                ('experience_quatre', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_quatre_description', models.TextField(blank=True, null=True)),
                ('competence_une_titre', models.CharField(blank=True, max_length=100, null=True)),
                ('competence_une_score', models.IntegerField(default=1)),
                ('competence_deux_titre', models.CharField(blank=True, max_length=100, null=True)),
                ('competence_deux_score', models.IntegerField(default=1)),
                ('competence_trois_titre', models.CharField(blank=True, max_length=100, null=True)),
                ('competence_trois_score', models.IntegerField(default=1)),
                ('competence_quatre_titre', models.CharField(blank=True, max_length=100, null=True)),
                ('competence_quatre_score', models.IntegerField(default=1)),
                ('mots_clees', models.CharField(blank=True, max_length=50, null=True)),
                ('siret', models.IntegerField(blank=True, null=True)),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyUser')),
            ],
        ),
    ]
